# Generated by Django 2.0.6 on 2018-06-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
