# Generated by Django 2.0.6 on 2018-06-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20180628_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='task',
            field=models.CharField(max_length=50),
        ),
    ]
