# Generated by Django 2.0.7 on 2018-07-06 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0006_auto_20180706_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertotask',
            name='user',
        ),
        migrations.AddField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserToTask',
        ),
    ]
